# Generates CraftHouse/data.lua: every profession recipe of the OctoWoW
# client (Spell.dbc + SkillLineAbility.dbc), item names from pfQuest's
# databases, and stats/level/quality/category learned from CraftHouse
# saved variables (the client files do not contain item stats).
#
# Usage: python gen_db.py <path to data.lua> [CraftHouse.lua saved vars ...]
import sys, os, re, hashlib
from dbc import load

ADDONS = r"D:\Games\OctoWoW - HD Upgrade\Interface\AddOns"

sk, skn = load('SkillLine.dbc')
SKILL = {r[0]: skn(r[3]) for r in sk}
sla, _ = load('SkillLineAbility.dbc')
sp, spn = load('Spell.dbc')
S = {r[0]: r for r in sp}
fo, fon = load('SpellFocusObject.dbc')
FOCUS = {r[0]: fon(r[1]) for r in fo}

# skill id -> profession name as GetTradeSkillLine/GetCraftDisplaySkillLine report it
PROF_SKILLS = [164, 165, 171, 185, 186, 197, 202, 333, 129, 755, 40, 142]

CREATE_ITEM, ENCHANT_ITEM, ENCHANT_TEMP = 24, 53, 54


def lua_str(s):
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'


# ---------------------------------------------------------------- item names
NAMES = {}
pat = re.compile(r'^\s*\[(\d+)\]\s*=\s*"((?:[^"\\]|\\.)*)"', re.M)
for path in [os.path.join(ADDONS, 'pfQuest', 'db', 'enUS', 'items.lua'),
             os.path.join(ADDONS, 'pfQuest-octo', 'db', 'enUS', 'items-turtle.lua')]:
    if os.path.exists(path):
        txt = open(path, encoding='utf-8', errors='replace').read()
        for m in pat.finditer(txt):
            NAMES[int(m.group(1))] = m.group(2).replace("\\'", "'").replace('\\"', '"')

# ---------------------------------------------------------------- learned data from saved variables
LEARNED = {}    # (prof, name) -> rec dict
LEARNED_ID = {} # (prof, itemid) -> rec dict
LEARNED_ITEM = {} # itemid -> stats learned from tooltips (CraftHouseDB.learned)
if len(sys.argv) > 2:
    from lupa import LuaRuntime
    for sv in sys.argv[2:]:
        L = LuaRuntime(unpack_returned_tuples=True)
        L.execute(open(sv, encoding='utf-8', errors='replace').read())
        db = L.eval('CraftHouseDB')

        def walk_char(c):
            if not c or not c['profs']:
                return
            for prof, p in c['profs'].items():
                if not p or not p['recipes']:
                    continue
                for r in p['recipes'].values():
                    d = {'n': r['n'], 'id': r['id'] or 0, 'q': r['q'], 'l': r['l'], 'c': r['c'],
                         'sl': r['sl'], 't': dict(r['t'].items()) if r['t'] else {}}
                    for x in (r['r'] or {}).values():
                        if x[3] and x[1]:
                            NAMES.setdefault(int(x[1]), x[3])
                    old = LEARNED.get((prof, d['n']))
                    # prefer entries with stats
                    if not old or (not old['t'] and d['t']):
                        LEARNED[(prof, d['n'])] = d
                        if d['id']:
                            LEARNED_ID[(prof, d['id'])] = d
                    if d['id']:
                        NAMES.setdefault(int(d['id']), d['n'])

        for iid, x in (db['learned'] or {}).items():
            if x and x['t']:
                LEARNED_ITEM[int(iid)] = {'n': '', 'id': int(iid), 'q': x['q'], 'l': x['l'], 'c': x['c'], 'sl': None,
                                          't': dict(x['t'].items())}
        for realm in (db['chars'] or {}).values():
            for c in realm.values():
                walk_char(c)
        for realm in (db['others'] or {}).values():
            for c in realm.values():
                walk_char(c)

# ---------------------------------------------------------------- recipes
profs = {}
seen = set()
for r in sla:
    skill, sid = r[1], r[2]
    if skill not in PROF_SKILLS or sid not in S or (skill, sid) in seen:
        continue
    s = S[sid]
    effects = s[61:64]
    reag = [(s[42 + i], s[50 + i]) for i in range(8) if s[42 + i]]
    item = 0
    made = 1
    for k in range(3):
        if effects[k] == CREATE_ITEM and s[103 + k]:
            item = s[103 + k]
            made = max(1, s[76 + k] + 1)
            break
    is_enchant = any(e in (ENCHANT_ITEM, ENCHANT_TEMP) for e in effects)
    if not reag and not item:
        continue
    if not item and not is_enchant and skill != 186:
        continue
    seen.add((skill, sid))
    name = spn(s[120])
    pname = SKILL[skill]
    tools = [s[40], s[41]]
    rec = dict(sid=sid, name=name, item=item, made=made, yellow=r[11], grey=r[10],
               reag=reag, tools=[t for t in tools if t], focus=FOCUS.get(s[15], '') if s[15] else '',
               enchant=is_enchant and not item)
    profs.setdefault(pname, []).append(rec)

total = 0
lines = []
lines.append('-- Generated by tools/gen_db.py from the OctoWoW client (Spell.dbc,')
lines.append('-- SkillLineAbility.dbc), pfQuest item names and learned CraftHouse scans.')
lines.append('-- Do not edit by hand.')
lines.append('')
lines.append('CraftHouse_DB = { profs = {}, items = {} }')
lines.append('local P, I = CraftHouse_DB.profs, CraftHouse_DB.items')
lines.append('')
used_items = set()
vsrc = []
for pname in sorted(profs):
    lst = sorted(profs[pname], key=lambda x: x['sid'])
    lines.append('-- %s: %d recipes' % (pname, len(lst)))
    lines.append('P[%s] = {' % lua_str(pname))
    for rec in lst:
        # learned stats (by product item, else by name)
        ld = ((rec['item'] and LEARNED_ID.get((pname, rec['item']))) or LEARNED.get((pname, rec['name']))
              or (rec['item'] and LEARNED_ITEM.get(rec['item'])))
        reag = '/'.join('%d*%d' % x for x in rec['reag'])
        for x in rec['reag']:
            used_items.add(x[0])
        for t in rec['tools']:
            used_items.add(t)
        if rec['item']:
            used_items.add(rec['item'])
        stats = ''
        q = l = c = sl = ''
        if ld:
            stats = '/'.join('%s=%s' % (k, (int(v) if float(v) == int(v) else v)) for k, v in sorted(ld['t'].items()))
            q = ld['q'] if ld['q'] is not None else ''
            l = ld['l'] if ld['l'] else ''
            c = ld['c'] or ''
            sl = ld['sl'] or ''
        tools = ','.join(str(t) for t in rec['tools'])
        # { spell, name, item, made, yellow, grey, reagents, tools, focus, quality, level, category, slot, stats }
        lines.append('  {%d,%s,%d,%d,%d,%d,"%s","%s",%s,%s,%s,%s,%s,"%s"},' % (
            rec['sid'], lua_str(rec['name']), rec['item'], rec['made'], rec['yellow'], rec['grey'],
            reag, tools, lua_str(rec['focus']), q if q != '' else 'nil', l if l != '' else 'nil',
            lua_str(c) if c else 'nil', lua_str(sl) if sl else 'nil', stats))
        vsrc.append('%s:%d' % (pname, rec['sid']))
        total += 1
    lines.append('}')
lines.append('')
missing = 0
for iid in sorted(used_items):
    if iid in NAMES:
        lines.append('I[%d] = %s' % (iid, lua_str(NAMES[iid])))
    else:
        missing += 1
# the version only depends on the recipe list (used for share keys)
ver = hashlib.md5(';'.join(vsrc).encode()).hexdigest()[:8]
lines.insert(5, 'CraftHouse_DB_VERSION = "%s"' % ver)
open(sys.argv[1], 'w', encoding='utf-8', newline='\n').write('\n'.join(lines) + '\n')
print('recipes', total, 'professions', {p: len(v) for p, v in profs.items()})
print('items named', len(used_items) - missing, 'missing names', missing)
print('with learned stats', sum(1 for l in lines if l.endswith('"},') and not l.endswith(',""},')))
print('version', ver)
